Update ci_cd.yml

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -163,45 +163,7 @@ jobs:
       - name: Public IP
         id: ip-address
         uses: haythem/public-ip@v1.2
-      
-      - name: Grant AWS SSH access
-        id: aws-ssh-access
-        run: |
-          # if [ ! -z "$DEPLOYMENTS" ]; then
-          if [ -z "$DEPLOYMENTS" ]; then
-            if [ ! -z "$AWS_KEY" -a ! -z "$AWS_SECRET" ]; then
-              if [ -z "$AWS_REGION" ]; then
-                AWS_REGION="eu-west-1"
-              fi
-              echo "Logging into AWS"
-              aws configure set aws_access_key_id $AWS_KEY
-              aws configure set aws_secret_access_key $AWS_SECRET
-              aws sts get-caller-identity 1>/dev/null 2>/dev/null
-              if [ $? -ne 0 ]; then
-                echo "Failed to login to AWS"
-                exit 1
-              else
-                echo "Login succeeded"
-              fi
-              # Add this github runner to ssh-access security group for SSH access
-              aws ec2 authorize-security-group-ingress --group-name ssh-access --protocol tcp --port 22 --cidr $IPV4/32
-              if [ $? -ne 0 ]; then
-                echo "SSH Access failed might not be able to SSH into host(s)"
-              else
-                echo "SSH Access granted for this runner"
-                echo "::set-output name=sg-set::true"
-              fi
-            fi
-          fi
-          exit 1
-        env:
-          IPV4: ${{ steps.ip-address.outputs.ipv4 }}
-          IPV6: ${{ steps.ip-address.outputs.ipv6 }}
-          AWS_KEY: ${{ steps.inputs-and-secrets.outputs.AWS_KEY }}
-          AWS_SECRET: ${{ steps.inputs-and-secrets.outputs.AWS_SECRET }}
-          AWS_REGION: ${{ steps.inputs-and-secrets.outputs.AWS_REGION }}
-          DEPLOYMENTS: ${{ steps.deployments.outputs.value }}
-          
+               
       - name: Checkout
         uses: actions/checkout@v2
         with:
@@ -661,6 +623,43 @@ jobs:
         if: steps.deployment-docker-command.outputs.value != ''
         run: |
           ${{ steps.deployment-docker-command.outputs.value }}
+
+      - name: Grant AWS SSH access
+        id: aws-ssh-access
+        run: |
+          # if [ ! -z "$DEPLOYMENTS" ]; then
+          if [ -z "$DEPLOYMENTS" ]; then
+            if [ ! -z "$AWS_KEY" -a ! -z "$AWS_SECRET" ]; then
+              if [ -z "$AWS_REGION" ]; then
+                AWS_REGION="eu-west-1"
+              fi
+              echo "Logging into AWS"
+              aws configure set aws_access_key_id $AWS_KEY
+              aws configure set aws_secret_access_key $AWS_SECRET
+              aws sts get-caller-identity 1>/dev/null 2>/dev/null
+              if [ $? -ne 0 ]; then
+                echo "Failed to login to AWS"
+                exit 1
+              else
+                echo "Login succeeded"
+              fi
+              # Add this github runner to ssh-access security group for SSH access
+              aws ec2 authorize-security-group-ingress --group-name ssh-access --protocol tcp --port 22 --cidr $IPV4/32
+              if [ $? -ne 0 ]; then
+                echo "SSH Access failed might not be able to SSH into host(s)"
+              else
+                echo "SSH Access granted for this runner"
+                echo "::set-output name=sg-set::true"
+              fi
+            fi
+          fi
+        env:
+          IPV4: ${{ steps.ip-address.outputs.ipv4 }}
+          IPV6: ${{ steps.ip-address.outputs.ipv6 }}
+          AWS_KEY: ${{ steps.inputs-and-secrets.outputs.AWS_KEY }}
+          AWS_SECRET: ${{ steps.inputs-and-secrets.outputs.AWS_SECRET }}
+          AWS_REGION: ${{ steps.inputs-and-secrets.outputs.AWS_REGION }}
+          DEPLOYMENTS: ${{ steps.deployments.outputs.value }}
 
       - name: Do deployments
         if: steps.deployments.outputs.value != ''
