Fix dispatching deployments

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -2,38 +2,18 @@ name: Deployment
 on:
   workflow_call:
     inputs:
-      ENVIRONMENT:
-        description: Environment (.env) file to use.
+      INPUTS:
         type: string
-        required: false
-      OR_HOSTNAME:
-        description: Instance to deploy to.
-        type: string
-        required: false
-      OR_ADMIN_PASSWORD:
-        description: Configure OR_ADMIN_PASSWORD or override .env value
-        type: string
-        required: false
-      CLEAN_INSTALL:
-        description: Delete Docker volumes (manager / postgres data)
-        type: string
-        default: 'false'
-      VERSION:
-        type: string
-        required: true
-      MANAGER_TAG:
-        type: string
-        required: false
-    secrets:
-      SECRETS:
-        required: false
 
 jobs:
   deployment:
-    name: "Deployment"
+    name: Deployment
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          lfs: true # Enable Git LFS plugin to fetch *.mbtiles
+
       - name: Get inputs and secrets
         id: inputs-and-secrets
         shell: python
@@ -46,6 +26,8 @@ jobs:
           inputs = os.getenv("INPUTS")
           secrets = os.getenv("SECRETS")
           eventName = os.getenv("GITHUB_EVENT_NAME")
+
+          print(eventName)
 
           if inputs is not None and inputs != '':
             inputs = json.loads(inputs)
@@ -83,8 +65,10 @@ jobs:
               else:
                   os.system(f"echo '{key}={value}' >> $GITHUB_OUTPUT")
         env:
+          CALLER_INPUTS: ${{ inputs.INPUTS }}
+          INPUTS: ${{ toJSON(github.event.inputs) }}
           SECRETS: ${{ toJSON(secrets) }}
-          INPUTS: ${{ toJSON(inputs) }}
+
       - name: Public IP
         id: ip-address
         shell: bash
@@ -105,36 +89,42 @@ jobs:
 
           echo "ipv4=$PUBLIC_IPV4" >> $GITHUB_OUTPUT
           echo "ipv6=$PUBLIC_IPV6" >> $GITHUB_OUTPUT
+
       - name: Check if main repo
         id: is_main_repo
-        run: |
-          if [ -f manager/src/main/java/org/openremote/manager/Main.java ]; then
-            echo "value=true" >> $GITHUB_OUTPUT
-          else
-            if [ -e 'openremote' ]; then
-              echo "::error::openremote submodule no longer supported, see custom project template!"
-              exit 1
-            fi
+        uses: ./.github/actions/check-if-main-repo
 
-            echo "value=false" >> $GITHUB_OUTPUT
-            echo "repository=$(sed -E 's#(.+)/.+#\1/openremote#' <<< $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT
-
-            version=$(cat gradle.properties | grep openremoteVersion | sed -E 's#.+=(.+)#\1#' | xargs)
-
-            if [ -z "$version" ]; then
-              echo "openremoteVersion must be set in gradle.properties"
-              exit 1
-            fi
-
-            echo "ref=$version" >> $GITHUB_OUTPUT
-          fi
       - name: Check ci_cd existence
         id: check_cicd_json
         uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
         with:
           files: ".ci_cd/ci_cd.json"
+
+      - name: Set up JDK 21 and gradle cache
+        id: java
+        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
+        with:
+          distribution: temurin
+          java-version: 21
+          cache: gradle
+
+      - name: Get version details
+        id: get-version-details
+        run: |
+          set -o pipefail # exit build with error when pipes fail
+          ./gradlew currentVersion | tee /tmp/currentVersion
+          versionWithQualifier=$(grep "Project version" /tmp/currentVersion | sed 's#Project version: ##')
+          version=$(sed -E 's#-.+##' <<< $versionWithQualifier)
+          isRelease=false
+          if [ "$version" == "$versionWithQualifier" ]; then
+            isRelease=true
+          fi
+          echo "version=$version" >> $GITHUB_OUTPUT
+          echo "version_with_qualifier=$versionWithQualifier" >> $GITHUB_OUTPUT
+          echo "is_release=$isRelease" >> $GITHUB_OUTPUT
+
       - name: Process ci_cd.json file
-        if: ${{ steps.check_cicd_json.outputs.files_exists == 'true' }}
+        if: ${{ steps.check_cicd_json.outputs.files_exists == 'true' && (github.ref_type == 'tag' || (github.event_name != 'workflow_dispatch' && github.event_name != 'pull_request')) }}
         id: ci-cd-output
         shell: python
         run: |
@@ -242,7 +232,8 @@ jobs:
           IS_MAIN_REPO: ${{ steps.is_main_repo.outputs.value }}
           MANAGER_VERSION: ${{ steps.is_main_repo.outputs.ref }}
           IS_RELEASE: ${{ steps.get-version-details.outputs.is_release }}
-          VERSION: ${{ inputs.VERSION }}
+          VERSION: ${{ steps.get-version-details.outputs.version }}
+
       - name: Sanitize deployments value
         id: deployments
         shell: python
@@ -287,6 +278,97 @@ jobs:
           INPUT_ENVIRONMENT: ${{ steps.inputs-and-secrets.outputs.ENVIRONMENT }}
           INPUT_MANAGER_TAG: ${{steps.inputs-and-secrets.outputs.MANAGER_TAG }}
           INPUT_PUSH_SNAPSHOT: ${{ steps.inputs-and-secrets.outputs.PUSH_SNAPSHOT }}
+
+      - name: Output image tag
+        id: get-image-tag
+        shell: bash
+        run: |
+          echo "refTag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+
+      - name: Install QEMU
+        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
+        with:
+          platforms: linux/aarch64 #,linux/amd64 Only ARM is currently in use
+
+      - name: Install Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
+
+      # --------------------------------------------------------------------------------------
+      # Download manager build directory
+      # --------------------------------------------------------------------------------------
+
+      - name: Define manager build path
+        id: define-manager-build-path
+        if: ${{ steps.is_main_repo.outputs.value == 'true' }}
+        shell: bash
+        run: |
+          buildPath="manager/build/install/manager"
+          echo "value=$buildPath" >> $GITHUB_OUTPUT
+        env:
+          DEPLOYMENTS: ${{ steps.deployments.outputs.value }}
+          MANAGER_TAGS: ${{ steps.ci-cd-output.outputs.dockerTags }}
+          PUSH_SNAPSHOT: ${{ steps.deployments.outputs.pushSnapshot }}
+
+      - name: Download manager build directory
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        if: ${{ steps.is_main_repo.outputs.value == 'true' }}
+        with:
+          name: or-manager-build
+          path: manager/build
+        continue-on-error: true
+
+      # --------------------------------------------------------------------------------------
+      # Download/build deployment build directory
+      # --------------------------------------------------------------------------------------
+
+      - name: Check deployment build.gradle
+        id: check_deployment_gradle
+        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
+        with:
+          files: "deployment/build.gradle"
+
+      - name: Check deployment dockerfile
+        id: check_deployment_dockerfile
+        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
+        with:
+          files: "deployment/Dockerfile"
+
+      - name: Define deployment build path
+        id: define-deployment-build-path
+        shell: bash
+        run: |
+          if [ "$DEPLOYMENT_DOCKERFILE_EXISTS" == 'true' ]; then
+            if [ "$DEPLOYMENT_GRADLE_EXISTS" != 'true' ]; then
+              echo "Deployment must have a build.gradle file to prepare the deployment files in the deployment/build dir"
+              exit 1
+            fi
+            echo "value=deployment/build" >> $GITHUB_OUTPUT
+          fi
+        env:
+          DEPLOYMENTS: ${{ steps.deployments.outputs.value }}
+          DEPLOYMENT_DOCKERFILE_EXISTS: ${{ steps.check_deployment_dockerfile.outputs.files_exists }}
+          DEPLOYMENT_GRADLE_EXISTS: ${{ steps.check_deployment_gradle.outputs.files_exists }}
+
+      - name: Download deployment build directory
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          name: or-deployment-build # Shouldn't exist in custom projects
+          path: deployment/build
+        continue-on-error: true
+
+      # This step is only meant to be run for projects which don't build the manager beforehand i.e.
+      # custom projects, as they wouldn't have a deployment/build dir
+      - name: Build deployment if missing
+        if: hashFiles('deployment/build/**') == ''
+        shell: bash
+        run: |
+          ./gradlew -p deployment installDist # TODO: optimize the task graph
+
+      # --------------------------------------------------------------------------------------
+      # Deploy
+      # --------------------------------------------------------------------------------------
+
       - name: Do deployments
         shell: python
         run: |
@@ -415,8 +497,11 @@ jobs:
         env:
           IS_MAIN_REPO: ${{ steps.is_main_repo.outputs.value }}
           DEPLOYMENTS: ${{ steps.deployments.outputs.value }}
-          MANAGER_REF: ${{steps.inputs-and-secrets.outputs.MANAGER_TAG }}
-          DEPLOYMENT_REF: ${{steps.inputs-and-secrets.outputs.MANAGER_TAG }}
+          BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
+          MANAGER_DOCKER_BUILD_PATH: ${{ steps.define-manager-build-path.outputs.value }}
+          DEPLOYMENT_DOCKER_BUILD_PATH: ${{ steps.define-deployment-build-path.outputs.value }}
+          MANAGER_REF: ${{steps.get-image-tag.outputs.refTag }}
+          DEPLOYMENT_REF: ${{ steps.get-image-tag.outputs.refTag }}
           INPUTS_AND_SECRETS: ${{ toJSON(steps.inputs-and-secrets.outputs) }}
           IPV4: ${{ steps.ip-address.outputs.ipv4 }}
           IPV6: ${{ steps.ip-address.outputs.ipv6 }}
