wip

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -1,24 +1,32 @@
 name: Deployment
 on:
-  workflow_dispatch:
   workflow_call:
     inputs:
-      environment:
+      ENVIRONMENT:
         description: Environment (.env) file to use.
         type: string
         required: false
-      hostname:
+      OR_HOSTNAME:
         description: Instance to deploy to.
         type: string
-        required: true
-      password:
+        required: false
+      OR_ADMIN_PASSWORD:
         description: Configure OR_ADMIN_PASSWORD or override .env value
         type: string
         required: false
-      clean_install:
+      CLEAN_INSTALL:
         description: Delete Docker volumes (manager / postgres data)
-        type: boolean
-        default: false
+        type: string
+        default: 'false'
+      VERSION:
+        type: string
+        required: true
+      MANAGER_TAG:
+        type: string
+        required: false
+    secrets:
+      SECRETS:
+        required: false
 
 jobs:
   deployment:
@@ -26,4 +34,389 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-      - run: echo 'test'
+      - name: Get inputs and secrets
+        id: inputs-and-secrets
+        shell: python
+        run: |
+          import os
+          import json
+
+          # Overlay all inputs and secrets onto this jobs outputs
+          callerInputs = os.getenv("CALLER_INPUTS")
+          inputs = os.getenv("INPUTS")
+          secrets = os.getenv("SECRETS")
+          eventName = os.getenv("GITHUB_EVENT_NAME")
+
+          if inputs is not None and inputs != '':
+            inputs = json.loads(inputs)
+          if secrets is not None and secrets != '':
+            secrets = json.loads(secrets)
+          if eventName == 'workflow_call' and callerInputs is not None and callerInputs != 'null':
+            os.system(f"echo 'Processing caller inputs'")
+            inputs = json.loads(callerInputs)
+
+          if inputs is not None and 'INPUTS' in inputs:
+            os.system("echo 'Processing inputs from caller'")
+            inputs = json.loads(inputs['INPUTS'])
+          if 'SECRETS' in secrets:
+            os.system("echo 'Processing secrets from caller'")
+            secrets = json.loads(secrets['SECRETS'])
+
+          # Iterate over secrets then inputs and assign them as outputs on this step
+
+          if secrets is not None and secrets != 'null':
+            for key, value in secrets.items():
+              print(f"::add-mask::{value}")
+              lines = len(value.split("\n"))
+              if lines > 1:
+                  os.system(f"echo '{key}<<EEOOFF\n{value}\nEEOOFF' >> $GITHUB_OUTPUT")
+              else:
+                  os.system(f"echo '{key}={value}' >> $GITHUB_OUTPUT")
+
+          if inputs is not None and inputs != 'null':
+            for key, value in inputs.items():
+              print(f"::add-mask::{value}")
+              os.system(f"echo 'Outputting input: {key}'")
+              lines = len(value.split("\n"))
+              if lines > 1:
+                  os.system(f"echo '{key}<<EEOOFF\n{value}\nEEOOFF' >> $GITHUB_OUTPUT")
+              else:
+                  os.system(f"echo '{key}={value}' >> $GITHUB_OUTPUT")
+        env:
+          SECRETS: ${{ toJSON(secrets) }}
+          INPUTS: ${{ toJSON(inputs) }}
+      - name: Public IP
+        id: ip-address
+        shell: bash
+        run: |
+          OPTS="-sf -m 5"
+
+          # Try Primary v4 -> Fallback v4 -> Default to empty
+          PUBLIC_IPV4=$(curl $OPTS v4.ident.me || curl $OPTS 4.tnedi.me || true)
+
+          # Try Primary v6 -> Fallback v6 -> Default to empty
+          PUBLIC_IPV6=$(curl $OPTS v6.ident.me || curl $OPTS 6.tnedi.me || true)
+
+          # Validation: Ensure at least one IP was found
+          if [[ -z "$PUBLIC_IPV4" && -z "$PUBLIC_IPV6" ]]; then
+          echo "::error::Could not determine Public IP (both v4 and v6 failed)."
+          exit 1
+          fi
+
+          echo "ipv4=$PUBLIC_IPV4" >> $GITHUB_OUTPUT
+          echo "ipv6=$PUBLIC_IPV6" >> $GITHUB_OUTPUT
+      - name: Check if main repo
+        id: is_main_repo
+        run: |
+          if [ -f manager/src/main/java/org/openremote/manager/Main.java ]; then
+            echo "value=true" >> $GITHUB_OUTPUT
+          else
+            if [ -e 'openremote' ]; then
+              echo "::error::openremote submodule no longer supported, see custom project template!"
+              exit 1
+            fi
+
+            echo "value=false" >> $GITHUB_OUTPUT
+            echo "repository=$(sed -E 's#(.+)/.+#\1/openremote#' <<< $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT
+
+            version=$(cat gradle.properties | grep openremoteVersion | sed -E 's#.+=(.+)#\1#' | xargs)
+
+            if [ -z "$version" ]; then
+              echo "openremoteVersion must be set in gradle.properties"
+              exit 1
+            fi
+
+            echo "ref=$version" >> $GITHUB_OUTPUT
+          fi
+      - name: Check ci_cd existence
+        id: check_cicd_json
+        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
+        with:
+          files: ".ci_cd/ci_cd.json"
+      - name: Process ci_cd.json file
+        if: ${{ steps.check_cicd_json.outputs.files_exists == 'true' }}
+        id: ci-cd-output
+        shell: python
+        run: |
+          import json
+          import os
+
+          eventName = os.getenv('GITHUB_EVENT_NAME')
+          refName = os.getenv('GITHUB_REF_NAME')
+          refType = os.getenv('GITHUB_REF_TYPE')
+          repoOwner = os.getenv('GITHUB_REPOSITORY_OWNER')
+          isMainRepo = os.getenv('IS_MAIN_REPO') == 'true'
+          isRelease = os.getenv('IS_RELEASE') == 'true'
+          managerVersion = os.getenv('MANAGER_VERSION')
+          version = os.getenv('VERSION')
+          deploys = None
+          dockerPublishTags = None
+          mavenPublishTag = None
+          npmPublishTag = None
+          deployEnvironment = None
+          eventConfig = ()
+
+          f = open(".ci_cd/ci_cd.json")
+          data = json.load(f)
+          f.close()
+
+          if isRelease:
+            eventName = "release"
+
+          if data is not None and eventName in data:
+            eventConfig = data[eventName]
+
+          if eventName == "push" and refType == "branch" and refName in eventConfig:
+            eventConfig = eventConfig[refName]
+
+          if eventConfig is not None:
+            deploys = eventConfig['deploy'] if 'deploy' in eventConfig else None
+            if 'distribute' in eventConfig:
+              if 'docker' in eventConfig['distribute']:
+                 dockerPublishTags = eventConfig['distribute']['docker']
+              if 'maven' in eventConfig['distribute']:
+                 mavenPublishTag = eventConfig['distribute']['maven']
+              if 'npm' in eventConfig['distribute']:
+                 npmPublishTag = eventConfig['distribute']['npm']
+
+          if isMainRepo and ((eventName == "release" and isRelease) or (eventName != "release" and not isRelease)):
+
+            if dockerPublishTags is not None:
+              if "$version" in dockerPublishTags:
+                 firstDockerTag = version
+                 dockerPublishTags = dockerPublishTags.replace("$version", version)
+              else:
+                dockerPublishTags = dockerPublishTags.replace("$version", version)
+                firstDockerTag = dockerPublishTags.split(",")[0]
+
+              os.system(f"echo 'firstDockerTag={firstDockerTag}' >> $GITHUB_OUTPUT")
+              os.system(f" echo 'Manager tags to push to docker hub: {dockerPublishTags}'")
+              dockerPublishTags = " ".join(map(lambda t: f"-t openremote/manager:{t.strip()}", dockerPublishTags.split(",")))
+              if repoOwner == 'openremote':
+                os.system(f"echo 'dockerTags={dockerPublishTags}' >> $GITHUB_OUTPUT")
+
+            if mavenPublishTag is not None and repoOwner == 'openremote':
+              mavenPublishTag = mavenPublishTag.replace("$version", version)
+              os.system(f" echo 'Maven publish version: {mavenPublishTag}'")
+              os.system(f"echo 'mavenTag={mavenPublishTag}' >> $GITHUB_OUTPUT")
+
+            if npmPublishTag is not None and repoOwner == 'openremote':
+              npmPublishTag = npmPublishTag.replace("$version", version)
+              os.system(f" echo 'npm publish version: {npmPublishTag}'")
+              os.system(f"echo 'npmTag={npmPublishTag}' >> $GITHUB_OUTPUT")
+
+          deployStr = None
+          if deploys is not None and repoOwner == 'openremote':
+            if not isinstance(deploys, list):
+              deploys = [deploys]
+
+            deployStr = ""
+            managerTagDefault = '#ref'
+
+            for deploy in deploys:
+              if 'environment' in deploy:
+                deployStr += deploy['environment']
+              deployStr += ":"
+              if 'managerTag' in deploy:
+                if isMainRepo:
+                  deployStr += deploy['managerTag']
+                else:
+                  # Custom projects manager docker image must match the openremoteVersion from gradle.properties
+                  deployStr += managerVersion
+              else:
+                if isMainRepo:
+                  os.system("echo 'Manager tag not specified so using commit SHA'")
+                  deployStr += managerTagDefault
+                else:
+                  # Custom projects manager docker image must match the openremoteVersion from gradle.properties
+                  deployStr += managerVersion
+
+              deployStr += ";"
+
+            deployStr = deployStr.rstrip(";")
+
+          if deployStr is not None and len(deployStr) > 0:
+            print(f"Deployments to deploy: {deployStr}")
+            os.system(f"echo 'deploys={deployStr}' >> $GITHUB_OUTPUT")
+        env:
+          IS_MAIN_REPO: ${{ steps.is_main_repo.outputs.value }}
+          MANAGER_VERSION: ${{ steps.is_main_repo.outputs.ref }}
+          IS_RELEASE: ${{ steps.get-version-details.outputs.is_release }}
+          VERSION: ${{ inputs.VERSION }}
+      - name: Sanitize deployments value
+        id: deployments
+        shell: python
+        run: |
+          import os
+          import sys
+
+          repoOwner = os.getenv('GITHUB_REPOSITORY_OWNER')
+          isMainRepo = os.getenv('IS_MAIN_REPO') == 'true'
+          deployments = os.getenv('DEPLOYMENTS')
+          eventName = os.getenv('GITHUB_EVENT_NAME')
+          refType = os.getenv('GITHUB_REF_TYPE')
+          inputTag = os.getenv('MANAGER_TAG')
+          inputEnv = os.getenv('ENVIRONMENT')
+          managerVersion = os.getenv('MANAGER_VERSION')
+
+          if eventName == 'workflow_dispatch' and refType != 'tag' and repoOwner == 'openremote':
+            if isMainRepo:
+              tag=inputTag
+              if not inputTag:
+                tag='#ref'
+            else:
+              tag=managerVersion
+            deployments=f'{inputEnv}:{tag}'
+
+          if not isMainRepo:
+            if "-SNAPSHOT" in deployments:
+              os.system("echo 'SNAPSHOT manager docker images not currently supported for custom project deployment'")
+              sys.exit(1)
+          os.system(f"echo 'value={deployments}' >> $GITHUB_OUTPUT")
+
+          pushSnapshot = os.getenv('INPUT_PUSH_SNAPSHOT')
+          if pushSnapshot == 'true' and repoOwner != 'openremote':
+            os.system("echo 'Only Openremote organisation can push to ECR'")
+            sys.exit(1)
+          else:
+            os.system(f"echo 'pushSnapshot={pushSnapshot}' >> $GITHUB_OUTPUT")
+        env:
+          IS_MAIN_REPO: ${{ steps.is_main_repo.outputs.value }}
+          MANAGER_VERSION: ${{ steps.is_main_repo.outputs.ref }}
+          DEPLOYMENTS: ${{ steps.ci-cd-output.outputs.deploys }}
+          INPUT_ENVIRONMENT: ${{ steps.inputs-and-secrets.outputs.ENVIRONMENT }}
+          INPUT_MANAGER_TAG: ${{steps.inputs-and-secrets.outputs.MANAGER_TAG }}
+          INPUT_PUSH_SNAPSHOT: ${{ steps.inputs-and-secrets.outputs.PUSH_SNAPSHOT }}
+      - name: Do deployments
+        shell: python
+        run: |
+          import json
+          import os
+          import sys
+          import subprocess
+
+          deployments = os.getenv("DEPLOYMENTS")
+          deployments = deployments.split(";")
+          managerRef = os.getenv("MANAGER_REF")
+          deploymentRef = os.getenv("DEPLOYMENT_REF")
+          isMainRepo = os.getenv("IS_MAIN_REPO") == 'true'
+          inputsAndSecrets = json.loads(os.getenv("INPUTS_AND_SECRETS"))
+          ipv4 = os.getenv("IPV4")
+          ipv6 = os.getenv("IPV6")
+
+          failure = False
+
+          # Clean-up AWS credentials related variable that might have been set by Configure AWS Credentials for ECR upload
+          os.environ.pop("AWS_ACCESS_KEY_ID", None)
+          os.environ.pop("AWS_SECRET_ACCESS_KEY", None)
+          os.environ.pop("AWS_SESSION_TOKEN", None)
+
+          # Determine deploy script to use
+          deployScript = ".ci_cd/deploy.sh"
+
+          if not os.path.exists(deployScript) and not isMainRepo:
+            deployScript = "openremote/.ci_cd/deploy.sh"
+
+          if not os.path.exists(deployScript):
+            os.system(f"Deploy script not found '{deployScript}'")
+            sys.exit(1)
+
+          for deployment in deployments:
+            dep = deployment.split(":")
+            env = dep[0]
+            managerTag = dep[1]
+            managerTagFound = True
+
+            os.putenv("MANAGER_TAG", managerTag)
+            os.putenv("ENVIRONMENT", env)
+
+            # Clean stale ssh credentials and temp files
+            os.system("rm temp.env 2>/dev/null")
+            os.system("rm ssh.key 2>/dev/null")
+            os.system("rm -r temp 2>/dev/null")
+            os.system("mkdir temp")
+
+            # ------------------------------------------------------
+            # Output env variables to temp env file for POSIX shell
+            # ------------------------------------------------------
+
+            # Output inputs and secrets (spacial handling for SSH_KEY and some other variables)
+            # _$ENV_ prefixed keys are output last (to override any non env specific keys)
+            environment = (env if env else "").upper()
+            prefix = "_" + environment + "_"
+
+            for key, value in inputsAndSecrets.items():
+              if "." in key:
+                continue
+
+              envFile = "temp/env"
+
+              # Look for temp and env prefixed keys
+              if key.startswith("_"):
+                if key.startswith("_TEMP_"):
+                  key = key.replace("_TEMP_", "")
+                  envFile = "temp.env"
+                elif key.startswith(prefix):
+                  key = key.replace(prefix, "")
+                else:
+                  continue
+
+              if key == "github_token":
+                continue
+              else:
+                os.system(f"echo 'Secret found {key}...'")
+                if key == "SSH_KEY":
+                  os.system(f"echo \"{value}\" > ssh.key")
+                else:
+                  lines = len(value.split("\n"))
+                  if lines > 1:
+                      os.system(f"echo '{key}='\"'\"'' >> {envFile}")
+                      os.system(f"echo '{value}'\"'\"'' >> {envFile}")
+                  else:
+                      os.system(f"echo '{key}='\"'\"'{value}'\"'\"'' >> {envFile}")
+
+            # Output new line
+            os.system(f"echo '\n' >> {envFile}")
+
+            # Output env file if exists
+            if os.path.exists(".ci_cd/env/.env"):
+              os.system(f"echo 'Outputting .ci_cd/env/.env to temp/env'")
+              os.system("cat .ci_cd/env/.env >> temp/env")
+              # Output new line
+              os.system(f"echo '\n' >> {envFile}")
+
+            # Output environment specific env file if exists
+            if env is not None and env != '' and os.path.exists(f".ci_cd/env/{env}.env"):
+              os.system(f"echo 'Outputting .ci_cd/env/{env}.env to temp/env'")
+              os.system(f"cat .ci_cd/env/{env}.env >> temp/env")
+              # Output new line
+              os.system(f"echo '\n' >> {envFile}")
+
+            # Set CIDR environment variable
+            if ipv4 is not None and ipv4 != '':
+              os.putenv("CIDR", ipv4 + '/32')
+            elif ipv6 is not None and ipv6 != '':
+              os.putenv("CIDR", ipv6 + '/64')
+
+            # Execute deploy script
+            os.system(f"echo 'Executing deploy script for deployment: managerTag={managerTag} deploymentTag={deploymentRef} environment={env}'")
+            # Uncomment this in combination with the SSH debug step afterwards to debug deployment script
+            #sys.exit(0)
+            result = subprocess.run(f"bash {deployScript}", shell=True)
+
+            if result.returncode != 0:
+              os.system(f"echo 'Deployment failed: managerTag={managerTag} deploymentTag={deploymentRef} environment={env}'")
+              failure = True
+              continue
+
+          if failure == True:
+            os.system("echo 'One or more deployments failed'")
+            sys.exit(1)
+        env:
+          IS_MAIN_REPO: ${{ steps.is_main_repo.outputs.value }}
+          DEPLOYMENTS: ${{ steps.deployments.outputs.value }}
+          MANAGER_REF: ${{steps.inputs-and-secrets.outputs.MANAGER_TAG }}
+          DEPLOYMENT_REF: ${{steps.inputs-and-secrets.outputs.MANAGER_TAG }}
+          INPUTS_AND_SECRETS: ${{ toJSON(steps.inputs-and-secrets.outputs) }}
+          IPV4: ${{ steps.ip-address.outputs.ipv4 }}
+          IPV6: ${{ steps.ip-address.outputs.ipv6 }}
